services:
  mysql:
    image: mysql:8.0.37
    container_name: mysql-db
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 959697989900
      MYSQL_DATABASE: autobiography_db
      MYSQL_USER: ssafy
      MYSQL_PASSWORD: 959697989900
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    networks:
      - app-network

  redis:
    image: redis:7.2-alpine
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    networks:
      - app-network

  livekit:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    restart: always
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882"
    environment:
      - LIVEKIT_KEYS__0__API_KEY=devkey
      - LIVEKIT_KEYS__0__API_SECRET=secret
        # 2) 기본 STUN 서버 (구글 공개 서버)
      - LIVEKIT_ICE_SERVERS__0__URLS=stun:stun.l.google.com:19302

      # 3) (선택) 외부 TURN 서버 정보
      #- LIVEKIT_ICE_SERVERS__1__URLS=turn:turn.example.com:3478?transport=udp
      #- LIVEKIT_ICE_SERVERS__1__USERNAME=turnUser
      #- LIVEKIT_ICE_SERVERS__1__CREDENTIAL=turnPass

      # 4) (선택) LiveKit 내장 TURN 활성화
      #- LIVEKIT_TURN__ENABLED=true
      #- LIVEKIT_TURN__TLS_PORT=5349
      #- LIVEKIT_TURN__DOMAIN=turn.example.com
      #- LIVEKIT_TURN__CERT_FILE=/certs/turn.crt
      #- LIVEKIT_TURN__KEY_FILE=/certs/turn.key
    networks:
      - app-network

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
